image: rustlang/rust:nightly
stages:
  - build
  - test
  - release

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull-push
  paths:
    - target/
    - $CARGO_HOME

before_script:
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - apt-get update && apt-get install qemu && apt-get clean

build:build:
  stage: build
  cache:
    <<: *global_cache
  script:
    - rustc --version && cargo --version
    - cargo build --all

test:test_run:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  script:
    - rustc --version && cargo --version
    - cargo test --all

#release:generate_docs:
#  stage: release
#  cache:
#    <<: *global_cache
#  script:
#    - rustc --version && cargo --version
#    - cargo doc --no-deps
#    - mv target/doc public
#  artifacts:
#    paths:
#      - public
#  when: manual
#  only:
#    - master
