[package]
name = "fallout_os"
version = "0.0.1"
authors = ["Zacharie Corniere <cornierez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-serial", "stdio",
    "-display", "none"
]
test-success-exit-code = 33
test-timeout = 60

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"

[dependencies]
x86_64 = "0.12"
volatile = "0.2.6"

[dependencies.bootloader]
version = "0.9.8"
features = ["map_physical_memory"]

[dependencies.lazy_static]
version = "1"
features = ["spin_no_std"]

[dependencies.fallout_vga_buffer]
path = "./lib/vga_buffer/"

[dependencies.fallout_memory]
path = "./lib/memory/"

[dependencies.fallout_qemu]
path = "./lib/qemu/"

[dependencies.fallout_interrupt]
path = "./lib/interrupt/"

[dependencies.fallout_testing_framework]
path = "./lib/test_framework/"

[[test]]
name = "should_panic"
harness = false
[[test]]
name = "stack_overflow"
harness = false
