name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install rust component
      run: rustup component add rust-src && rustup component add llvm-tools-preview
    - name: install qemu
      run: apt-get update && apt-get install qemu && apt-get clean
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
